language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
script:
  - 'pipenv run coverage run --source=zephir-exports/lib -m pytest'
  - 'pipenv run codecov'
after_success:
    - bash <(curl -s https://codecov.io/bash)
