language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
script:
  - 'cd zephir-exports'
  - 'pipenv run coverage run --source=zephir-exports/lib -m pytest'
  - 'pipenv run coverage report --omit=*tests/*.py --fail-under=70'
