language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
  - 'pipenv install codecov'
script:
  - 'COVERAGE_FILE=.coverage_zephir-exports pipenv run coverage run --source=. -m pytest zephir-exports/lib'
  - 'COVERAGE_FILE=.coverage_zephir-exports pipenv run coverage report --omit=*/tests/*.py --fail-under=70'
  - 'COVERAGE_FILE=.coverage_zed-verify pipenv run coverage run --source=. -m pytest zed-verify'
  - 'COVERAGE_FILE=.coverage_zed-verify pipenv run coverage report --omit=*/tests/*.py --fail-under=70'
  - 'pipenv run coverage combine .coverage*'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
