language: python
python:
  - '3.6'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE htmm;'
install:
  - 'pip install pipenv'
  - 'pipenv install'
  - 'pipenv install codecov'
script:
  - 'pipenv run black --check zephir* zed*'
  - 'pipenv run flake8 * --ignore E501,W503 --exclude docs/,Pipfile,README.md,LICENSE,Pipfile.lock'
  - 'COVERAGE_FILE=.coverage_zephir-exports pipenv run coverage run --source=. -m pytest zephir-exports'
  - 'COVERAGE_FILE=.coverage_zephir-exports pipenv run coverage report --omit=*/tests/*.py --fail-under=10'
  - 'COVERAGE_FILE=.coverage_zed-verify pipenv run coverage run --source=. -m pytest zed-verify'
  - 'COVERAGE_FILE=.coverage_zed-verify pipenv run coverage report --omit=*/tests/*.py --fail-under=10'
  - 'COVERAGE_FILE=.coverage_zephir-cluster pipenv run coverage run --source=. -m pytest zephir-cluster'
  - 'COVERAGE_FILE=.coverage_zephir-cluster pipenv run coverage report --omit=*/tests/*.py --fail-under=10'
  - 'COVERAGE_FILE=.coverage_zephir-logger pipenv run coverage run --source=. -m pytest zed-event'
  - 'COVERAGE_FILE=.coverage_zephir-logger pipenv run coverage report --omit=*/tests/*.py --fail-under=10'
  - 'ls -all'
  - 'pipenv run coverage combine .coverage*'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
