language: python
python:
  - '3.6'
install:
  - 'pip install codecov'
  - 'pip install pipenv'
  - 'pipenv install'
script:
  - 'pipenv run pytest'
  - 'pipenv run codecov'
after_success:
    - bash <(curl -s https://codecov.io/bash)
