primary_db_path: /apps/htmm/leveldb/leveldb_files/primary-lookup 
cluster_db_path: /apps/htmm/leveldb/leveldb_files/cluster-lookup

logfile: /apps/htmm/log/cid_minting/cid_minting.log

zephir_files_dir: /apps/htmm/import

zed_log_path: /apps/htmm/log/zed/cid
zed_msg_table: /apps/htmm/cdl-env/zed/msg_tables/columns_prep.csv 
