#!/usr/bin/env python
import click

from validate import validate
from audit import audit


@click.group()
def entry_point():
    """A collection of utilities for verifying zed logs."""
    pass


entry_point.add_command(validate)
entry_point.add_command(audit)

if __name__ == "__main__":
    entry_point()
