import os
import shutil
import sys

import pytest


@pytest.fixture
def td_tmpdir(request, tmpdir, monkeypatch):
    """Copy test data into the temporary directory for tests.

    Note:
        1) Test data is located by convention. Create a directory with the same name as
        the test file (test-file: test_mymodule.py, test-data: test_mymodule/* )

    Args:
        request: Fixture with test case filename, used to find test data.
        tmpdir: Fixture for test case temporary directory generated by pytest.

    Returns:
        Filepath of test data subdirectory within the temporary dirctory.

    """
    td_dirname = os.path.splitext(os.path.basename(request.fspath))[0]
    td_path = os.path.join(os.path.dirname(__file__), td_dirname)
    tmp_td_path = os.path.join(tmpdir, td_dirname)
    shutil.copytree(td_path, tmp_td_path)
    # monkeypatch.setenv("PYTEST_TMPDIR", str(tmp_td_path))
    # if os.path.exists(os.path.join(str(tmp_td_path),'config')):
    #     monkeypatch.setenv("ZED_CONFIG", os.path.join(str(tmp_td_path),'config'))
    #     os.system("mysql --host=localhost --user=root  < {}/events.sql".format(tmp_td_path))
    return tmp_td_path


def pytest_configure(config):
    os.environ["ZED_ENV"] = "test"
    tmpdir = os.path.join(os.path.dirname(__file__), "tmp")
    if not os.path.exists(tmpdir):
        os.makedirs(tmpdir)
    return config


def pytest_unconfigure(config):
    os.environ["ZED_ENV"] = ""
    tmpdir = os.path.join(os.path.dirname(__file__), "tmp")
    if os.path.exists(tmpdir):
        shutil.rmtree(tmpdir)
    return config
