DROP TABLE IF EXISTS transactions;

CREATE TABLE IF NOT EXISTS transactions (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `publisher` varchar(50) NOT NULL DEFAULT '',
  `doi` varchar(50) NOT NULL DEFAULT '',
  `article_title` varchar(150) NOT NULL DEFAULT '',
  `corresponding_author` varchar(50) NOT NULL DEFAULT '',
  `corresponding_author_email` varchar(50) NOT NULL DEFAULT '',
  `uc_institution` varchar(50) NOT NULL DEFAULT '',
  `institution_identifier` varchar(50) NOT NULL DEFAULT '',
  `document Type` varchar(50) NOT NULL DEFAULT '',
  `eligible` varchar(50) NOT NULL DEFAULT '',
  `inclusion_date` varchar(50) NOT NULL DEFAULT '',
  `uc_approval_date` varchar(50) NOT NULL DEFAULT '',
  `article_access_type` varchar(50) NOT NULL DEFAULT '',
  `article_license` varchar(50) NOT NULL DEFAULT '',
  `journal_name` varchar(50) NOT NULL DEFAULT '',
  `issn_eissn` varchar(50) NOT NULL DEFAULT '',
  `journal_access_type` varchar(50) NOT NULL DEFAULT '',
  `journal_subject` varchar(50) NOT NULL DEFAULT '',
  `grant_participation` varchar(50) NOT NULL DEFAULT '',
  `funder_information` varchar(150) NOT NULL DEFAULT '',
  `full_coverage_reason` varchar(150) NOT NULL DEFAULT '',
  `original_apc_usd` varchar(50) NOT NULL DEFAULT '',
  `contractual_apc_usd` varchar(50) NOT NULL DEFAULT '',
  `library_apc_portion_usd` varchar(50) NOT NULL DEFAULT '',
  `author_apc_portion_usd` varchar(50) NOT NULL DEFAULT '',
  `payment_note` varchar(150) NOT NULL DEFAULT '',
  `cdl_notes` varchar(150) NOT NULL DEFAULT '',
  `license_chosen` varchar(50) NOT NULL DEFAULT '',
  `journal_bucket` varchar(50) NOT NULL DEFAULT '',
  `agreement_manager_profile_name` varchar(50) NOT NULL DEFAULT '',
  `publisher_status` varchar(50) NOT NULL DEFAULT '',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_edit` timestamp NOT NULL DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
