# COB transformer

source_fieldnames = [
        "Manuscript Name",
        "Manuscript DOI",
        "PII",
        "Manuscript ID",
        "CCC Manuscript ID",
        "Other Manuscript ID",
        "External Reference ID",
        "Manuscript Type",
        "Primary Author First Name",
        "Primary Author Middle Name",
        "Primary Author Last Name",
        "Primary Author Email Address",
        "Number of Pages",
        "Number of Color Figures",
        "Publication Name",
        "Publication ID",
        "Publication DOI",
        "Author Country",
        "ORCID",
        "RESEARCHERID",
        "Membership Name",
        "Geographic Location - used for discount",
        "Institution Identifier - from manuscript metadata",
        "Institution Name - from manuscript metadata",
        "Institution Affiliation - Ringgold ID",
        "Institution Affiliation - Ringgold Name",
        "Institution Affiliation used for discount - Ringgold ID",
        "Institution Affiliation used for discount - Ringgold Name",
        "Creative Commons License Type",
        "Other License Type",
        "Volume",
        "Issue",
        "Publisher Name",
        "Society Name",
        "Submission Date",
        "Date Manuscript Accepted",
        "Target Publication Date",
        "Target OA Publication Date",
        "Order Date",
        "Order ID",
        "Ordered By",
        "Order Reference Number",
        "Transaction Type",
        "Total Tax / VAT %",
        "Total Order Amount",
        "Currency",
        "Product 1 Name",
        "Product 1 Option 1",
        "Product 1 Option 1 Value",
        "Product 1 Option 1 Amount Before Discounts",
        "Product 1 Option 2",
        "Product 1 Option 2 Value",
        "Product 1 Option 2 Amount Before Discounts",
        "Product 1 Option 3",
        "Product 1 Option 3 Value",
        "Product 1 Option 3 Amount Before Discounts",
        "Product 1 Original Amount - before discounts",
        "Product 1 Geographic Discount",
        "Product 1 Membership Discount",
        "Product 1 Affiliation Discount",
        "Product 1 Promo Code Discount",
        "Product 1 Subtotal - before taxes",
        "Product 1 tax/VAT Percentage",
        "Product 1 Tax Amount",
        "Product 2 Name",
        "Product 2 Option 1",
        "Product 2 Option 1 Value",
        "Product 2 Option 1 Amount Before Discounts",
        "Product 2 Option 2",
        "Product 2 Option 2 Value",
        "Product 2 Option 2 Amount Before Discounts",
        "Product 2 Option 3",
        "Product 2 Option 3 Value",
        "Product 2 Option 3 Amount Before Discounts",
        "Product 2 Original Amount - before discounts",
        "Product 2 Geographic Discount",
        "Product 2 Membership Discount",
        "Product 2 Affiliation Discount",
        "Product 2 Promo Code Discount",
        "Product 2 Subtotal - before taxes",
        "Product 2 tax/VAT Percentage",
        "Product 2 Tax Amount",
        "Product 3 Name",
        "Product 3 Option 1",
        "Product 3 Option 1 Value",
        "Product 3 Option 1 Amount Before Discounts",
        "Product 3 Option 2",
        "Product 3 Option 2 Value",
        "Product 3 Option 2 Amount Before Discounts",
        "Product 3 Option 3",
        "Product 3 Option 3 Value",
        "Product 3 Option 3 Amount Before Discounts",
        "Product 3 Original Amount - before discounts",
        "Product 3 Geographic Discount",
        "Product 3 Membership Discount",
        "Product 3 Affiliation Discount",
        "Product 3 Promo Code Discount",
        "Product 3 Subtotal - before taxes",
        "Product 3 tax/VAT Percentage",
        "Product 3 Tax Amount",
        "Product 4 Name",
        "Product 4 Option 1",
        "Product 4 Option 1 Value",
        "Product 4 Option 1 Amount Before Discounts",
        "Product 4 Option 2",
        "Product 4 Option 2 Value",
        "Product 4 Option 2 Amount Before Discounts",
        "Product 4 Option 3",
        "Product 4 Option 3 Value",
        "Product 4 Option 3 Amount Before Discounts",
        "Product 4 Original Amount - before discounts",
        "Product 4 Geographic Discount",
        "Product 4 Membership Discount",
        "Product 4 Affiliation Discount",
        "Product 4 Promo Code Discount",
        "Product 4 Subtotal - before taxes",
        "Product 4 tax/VAT Percentage",
        "Product 4 Tax Amount",
        "Taxable Address",
        "Taxable Address Country",
        "Taxable Address State or Province",
        "Shipping Address",
        "Promotion Name",
        "Promotion Code(s) Applied",
        "Promotion Code(s) from manuscript metadata",
        "Total Discount",
        "Funding Request Profile Name",
        "Agreement Name",
        "Funding Status",
        "Funding Status Update Date",
        "Funding Deny Reason",
        "Funding Deny Reason Details",
        "Invoice Number",
        "Invoice Sequence No.",
        "Invoice Date",
        "Invoice Link",
        "Account No.",
        "Transaction Status",
        "Payment Method",
        "Payment Status",
        "Payment Close Date",
        "Payment Close Reason",
        "Payment Close Reason Updated",
        "Order Confirmation",
        "Funder 1 Name",
        ]


def source_to_output_mapping(row):
    output = {
        'Publisher': "CoB",
        'DOI': row['Manuscript DOI'],
        'Article Title': row['Manuscript Name'],
        'Corresponding Author': "{} {} {}".format(row['Primary Author First Name'], row['Primary Author Middle Name'], row['Primary Author Last Name']),
        'Corresponding Author Email': row['Primary Author Email Address'],
        'UC Institution': "",
        'Institution Identifier': "",
        'Document Type': row['Manuscript Type'],
        'Eligible': "Yes",
        'Inclusion Date': row['Date Manuscript Accepted'],
        'UC Approval Date': "",
        'Article Access Type': "OA",
        'Article License': row['Creative Commons License Type'],
        'Journal Name': row['Publication Name'],
        'ISSN/eISSN': row['Publication ID'],
        'Journal Access Type': "",
        'Journal Subject': "",
        'Grant Participation': row['Product 1 Option 2 Value'],
        'Funder Information': row['Funder 1 Name'],
        'Full Coverage Reason': row['Product 1 Option 3 Value'],
        'Original APC (USD)': "",
        'Contractual APC (USD)': "",
        'Library APC Portion (USD)': row['Total Discount'],
        'Author APC Portion (USD)': "",
        'Payment Note': "",
        }
    return output

